name: "Tesla BLE Home Assistant"
version: "0.0.3"
full_access: true
slug: "tesla_http_proxy"
description: "Tesla BLE Home Assistant"
url: "https://github.com/danielnitsche/tesla-ble-home-assistant/tree/main/tesla_http_proxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
startup: services
options:
  key_name: ""
  vin: ""
schema:
  key_name: "str"
  vin: "match(^[A-Z0-9]{17}$)"
ingress: true
panel_icon: mdi:forward
backup_exclude: 
  - /data/gnugpg
  - /data/password-store
hassio_api: true
stage: experimental
image: "ghcr.io/danielnitsche/tesla_http_proxy_{arch}"
